title: Ktecs
email: tyler.schiewe@gmail.com
description: Simple entity component system library for Kotlin
baseurl: "" # the subpath of your site, e.g. /blog
url: "tschie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tschie

livereload: true

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "View on GitHub":
    - "//github.com/tschie/ktecs"
