title: Ktecs
email: tyler.schiewe@gmail.com
description: Entity component system library for Kotlin
baseurl: "/ktecs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tschie

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "View on GitHub":
    - "//github.com/tschie/ktecs"
